spring.application.name=skillmatch-
# Server
server.port=8080

# PostgreSQL Ba?lant?s?
spring.datasource.url=jdbc:postgresql://localhost:5433/skillmatch
spring.datasource.username=skillmatch_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.security.headers.content-security-policy=script-src 'self' 'unsafe-inline'
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
